export const LOAD_LIST_OF_CRYPTOCURRENCYS_REQUEST = 'LOAD_LIST_OF_CRYPTOCURRENCYS_REQUEST';
export const UPDATE_LIST_OF_CRYPTOCURRENCYS_REQUEST = 'UPDATE_LIST_OF_CRYPTOCURRENCYS_REQUEST';
export const LOAD_LIST_OF_CRYPTOCURRENCYS_SUCCESS = 'LOAD_LIST_OF_CRYPTOCURRENCYS_SUCCESS';
export const UPDATE_LIST_OF_CRYPTOCURRENCYS_SUCCESS = 'UPDATE_LIST_OF_CRYPTOCURRENCYS_SUCCESS';
export const LOAD_LIST_OF_CRYPTOCURRENCYS_ERROR = 'LOAD_LIST_OF_CRYPTOCURRENCYS_ERROR';
export const UPDATE_LIST_OF_CRYPTOCURRENCYS_ERROR = 'UPDATE_LIST_OF_CRYPTOCURRENCYS_SUCCESS';
export const UPDATE_CURRENCY_REQUEST = 'UPDATE_CURRENCY_REQUEST';
export const UPDATE_CURRENCY_SUCCESS = 'UPDATE_CURRENCY_SUCCESS';
export const UPDATE_CURRENCY_ERROR = 'UPDATE_CURRENCY_ERROR';
export const REFRESH_CRYPTOCURRENCY_REQUEST = 'REFRESH_CRYPTOCURRENCY_REQUEST';
export const REFRESH_CRYPTOCURRENCY_SUCCESS = 'REFRESH_CRYPTOCURRENCY_SUCCESS';
export const REFRESH_CRYPTOCURRENCY_ERROR= 'REFRESH_CRYPTOCURRENCY_ERROR';

